--
--	NAO ESQUECA DE RODAR ESTE CODIGO PARA O SEU USUÁRIO E NAO SALVAR AS ALTERACOES NA HORA DO PUSH
--
-- APOS RODAR ESTE SCRIPT É NECESSÁRIO ACESSAR A NODEJS/SERVER.JS , DESCOMENTAR DA LINHA 59 A 126 E RODAR O NODE NOVAMENTE. APÓS ESSA EXECUCAO, DESCARTE A ALTERAÇÃO NO ARQUIVO NODEJS/SERVER.JS
INSERT INTO "VGT.USUARIO" VALUES("identity_VGT.USUARIO_id_usuario".nextval,'Nome do Usuario', 'email@email.com.br', '', 'UsuarioParaLogin', 'senha', true, 2);-- 2 é para admin full

-- Acesso a todos os módulos
INSERT INTO "VGT.REL_USUARIO_MODULO" VALUES(1,1);
INSERT INTO "VGT.REL_USUARIO_MODULO" VALUES(1,2);
INSERT INTO "VGT.REL_USUARIO_MODULO" VALUES(1,3);
INSERT INTO "VGT.REL_USUARIO_MODULO" VALUES(1,4);
INSERT INTO "VGT.REL_USUARIO_MODULO" VALUES(1,5);

-- PARA PERFIL DE ACESSO = 0 ESSAS DEFINICOES DE USUARIO POR EMPRESA SAO NECESSARIAS
-- PARA USUARIOS ADMINISTRADORES (PERFIL 1 OU 2) ESSES INSERTS ABAIXO NÃO SÃO UTILIZADOS
-- Incrementar para o número de empresas na base para usuarios
--INSERT INTO "VGT.REL_USUARIO_EMPRESA" VALUES(1,1);